### ISSUE TITLE
Non-descriptive error-message shown when non-RA log on

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/Stepup-RA#158]
Logging in as a non-RA(A) will lead to a generic error message:
![afbeelding](https://user-images.githubusercontent.com/841045/42410574-ce3846a6-81eb-11e8-8c0c-818b2b803304.png)
... and an exception raised in the logs:

> Jul  7 13:14:02 RA[3309]: {"channel":"app","level":"CRITICAL","message":"Uncaught PHP Exception Symfony\\Component\\Debug\\Exception\\ClassNotFoundException: \"Attempted to load class \"AccessDeniedException\" from namespace \"Surfnet\\StepupRa\\RaBundle\\Exception\".\nDid you forget a \"use\" statement for e.g. \"Symfony\\Component\\Finder\\Exception\\AccessDeniedException\", \"Symfony\\Component\\HttpFoundation\\File\\Exception\\AccessDeniedException\" or \"Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException\"?\" at /apps/programs/StepUp-RA/Stepup-RA-2.9.0/src/Surfnet/StepupRa/RaBundle/Security/Authentication/Provider/SamlProvider.php line 94","context":{"exception":{"class":"Symfony\\Component\\Debug\\Exception\\ClassNotFoundException","message":"Attempted to load class \"AccessDeniedException\" from namespace \"Surfnet\\StepupRa\\RaBundle\\Exception\".\nDid you forget a \"use\" statement for e.g. \"Symfony\\Component\\Finder\\Exception\\AccessDeniedException\", \"Symfony\\Component\\HttpFoundation\\File\\Exception\\AccessDeniedException\" or \"Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException\"?","code":0,"file":"/apps/programs/StepUp-RA/Stepup-RA-2.9.0/src/Surfnet/StepupRa/RaBundle/Security/Authentication/Provider/SamlProvider.php:94"}},"extra":{"art":"92211","server":"ra.stepup.moo-archive.nl","application":"registration-authority","request_id":"ce9fcb257ac195e8a74e5ff514692220"}}

Unfortunately the fix is not as easy as adding:
`use Symfony\Component\Security\Core\Exception\AccessDeniedException;`

.. as it will lead to the next exception:
> Jul  7 13:16:59 RA[3309]: {"channel":"app","level":"CRITICAL","message":"Uncaught PHP Exception Symfony\\Component\\Debug\\Exception\\FatalThrowableError: \"Type error: Argument 1 passed to Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException::setToken() must implement interface Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface, null given, called in /apps/programs/StepUp-RA/Stepup-RA-2.9.0/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php on line 123\" at /apps/programs/StepUp-RA/Stepup-RA-2.9.0/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php line 36","context":{"exception":{"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","message":"Type error: Argument 1 passed to Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException::setToken() must implement interface Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface, null given, called in /apps/programs/StepUp-RA/Stepup-RA-2.9.0/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php on line 123","code":0,"file":"/apps/programs/StepUp-RA/Stepup-RA-2.9.0/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Exception/AuthenticationException.php:36"}},"extra":{"art":"23470","server":"ra.stepup.moo-archive.nl","application":"registration-authority","request_id":"8f5da8a63d628dfae291dc38ddaebcf4"}}

**Comment by pmeulen** [comment]
The missing use was fixed https://github.com/OpenConext/Stepup-RA/pull/155 / https://www.pivotaltracker.com/story/show/158658721

I can confirm that an "Error - Oops!" is still shown when a user authenticates with a LoA 3 token to the RA (2.9.2) without the user having RA rights. 

https://www.pivotaltracker.com/story/show/158894749

**Comment by tvdijen** [comment]
Oh bite me, I totally missed that PR...

**Comment by tvdijen** [comment]
Fixed in #159
