### ISSUE TITLE
2.10.0: composer fails on dependencies

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/Stepup-RA#164]
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package ee/dataexporter-bundle **dev-feature/syfony-3-and-4-support** exists as ee/dataexporter-bundle[dev-develop, dev-master, v0.1, v0.2, v0.3, v0.4, v0.4.1, v0.4.2] but these are rejected by your constraint.

There is no such feature branch on that repo.. In fact, the repo seems abandoned.. Did you perhaps make a fork that needs to be included here @MKodde?

**Comment by MKodde** [comment]
I've released [2.10.1](https://github.com/OpenConext/Stepup-RA/releases/tag/2.10.1), that should remedy your problem

**Comment by tvdijen** [comment]
It did, thanks!
